# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [2]:
data = {'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'], 
        'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'], 
        'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
        'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]}

df_sales = pd.DataFrame(data)
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [5]:
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [6]:
total_units = df_sales['Units_Sold'].sum()
total_revenue = df_sales['Revenue'].sum() 

print(f'Total Units Sold: {total_units}')
print(f'Total Revenue: {total_revenue}')

Total Units Sold: 105
Total Revenue: 16000

In [8]:
avg_units = df_sales['Units_Sold'].mean()
avg_revenue = df_sales['Revenue'].mean()

print(f'Average Units Sold: {avg_units:.2f}')
print(f'Average Revenue: {avg_revenue:.2f}')

Average Units Sold: 11.67
Average Revenue: 1777.78

## Grouping Data

In [9]:
by_product =df_sales.groupby('Product')[['Units_Sold', 'Revenue']].sum()
print('Total by Product:')
by_product

Total by Product:

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [10]:
by_region = df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean()
print('Average by Region:')
by_region

Average by Region:

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [11]:
by_product_region = df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum()
print('Total by Product and Region:')
by_product_region

Total by Product and Region:

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [12]:
df_sales_sorted_units = df_sales.sort_values('Units_Sold', ascending=True)
print('Sorted by Units Sold (ascending):')
df_sales_sorted_units

Sorted by Units Sold (ascending):

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
0       A  North          10    100     1000
4       B  North          10    200     2000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [13]:
df_sales_sorted_revenue = df_sales.sort_values('Revenue', ascending=False)
print('Sorted by Revenue (desecending):')
df_sales_sorted_revenue

Sorted by Revenue (desecending):

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [14]:
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False).astype(int)
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000             7
1       B  South          15    200     3000             1
2       C   East          20    150     3000             1
3       A   West           5    100      500             9
4       B  North          10    200     2000             5
5       C  South          15    150     2250             3
6       A   East          10    100     1000             7
7       B   West           5    200     1000             7
8       C  North          15    150     2250             3

In [15]:
df_sales

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000             7
1       B  South          15    200     3000             1
2       C   East          20    150     3000             1
3       A   West           5    100      500             9
4       B  North          10    200     2000             5
5       C  South          15    150     2250             3
6       A   East          10    100     1000             7
7       B   West           5    200     1000             7
8       C  North          15    150     2250             3

## Merging DataFrames

In [16]:
product_data = {'Product': ['A', 'B', 'C'], 
                'Category': ['Electronics', 'Furniture', 'Appliances']}
df_products = pd.DataFrame(product_data)
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [17]:
df_merged = pd.merge(df_sales, df_products, on='Product')
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000             7  Electronics
1       B  South          15    200     3000             1    Furniture
2       C   East          20    150     3000             1   Appliances
3       A   West           5    100      500             9  Electronics
4       B  North          10    200     2000             5    Furniture
5       C  South          15    150     2250             3   Appliances
6       A   East          10    100     1000             7  Electronics
7       B   West           5    200     1000             7    Furniture
8       C  North          15    150     2250             3   Appliances

In [18]:
revenue_by_category = df_merged.groupby('Category')['Revenue'].sum()
print('Total Revenue by Category:')
revenue_by_category

Total Revenue by Category:

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64